# -*- coding: utf-8 -*-
"""T2_Tokenization_Embeddings_Similarity_Search_corrected.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbqMxO-eGKm90VsNtJI-JS9jC4hpUg0c
"""

# Commented out IPython magic to ensure Python compatibility.
# Install required libraries
# %pip install -q -U transformers sentence-transformers scikit-learn numpy

# Import libraries
from transformers import AutoTokenizer
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

print("Libraries imported successfully!")

# Load GPT-2 tokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")

print("GPT-2 tokenizer loaded successfully!")

# Tokenization example
text = "Generative AI is transforming education."

tokens = tokenizer.tokenize(text)
token_ids = tokenizer.encode(text, add_special_tokens=False)

print("Original text:")
print(text)

print("\nTokens:")
print(tokens)

print("\nToken IDs:")
print(token_ids)

print("\nNumber of tokens:", len(token_ids))

# Display each token with its ID
# Both lists are created without special tokens, so their lengths match.
for token, token_id in zip(tokens, token_ids):
    print(f"{repr(token)} -> {token_id}")

# More tokenization examples
examples = [
    "Artificial intelligence",
    "ArtificialIntelligence",
    "AI",
    "machine-learning",
    "unbelievable"
]

for sentence in examples:
    ids = tokenizer.encode(sentence, add_special_tokens=False)
    toks = tokenizer.tokenize(sentence)

    print("\nText:", sentence)
    print("Tokens:", toks)
    print("Token IDs:", ids)

# Load sentence-embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

# Generate embeddings
sentences = [
    "I love artificial intelligence.",
    "I am interested in machine learning.",
    "The weather is very pleasant today."
]

embeddings = embedding_model.encode(sentences)

print("Embedding shape:", embeddings.shape)
print("\nFirst 10 values of the first embedding:")
print(embeddings[0][:10])

# Compare sentence similarity
sentence_a = "I love artificial intelligence."
sentence_b = "I am interested in AI."
sentence_c = "The weather is rainy today."

test_embeddings = embedding_model.encode([
    sentence_a,
    sentence_b,
    sentence_c
])

similarity_ab = cosine_similarity(
    test_embeddings[0].reshape(1, -1),
    test_embeddings[1].reshape(1, -1)
)[0, 0]

similarity_ac = cosine_similarity(
    test_embeddings[0].reshape(1, -1),
    test_embeddings[2].reshape(1, -1)
)[0, 0]

print(f"Similarity between A and B: {similarity_ab:.4f}")
print(f"Similarity between A and C: {similarity_ac:.4f}")

# Similarity search
query = "What is artificial intelligence?"

documents = [
    "Artificial intelligence enables machines to perform tasks that normally require human intelligence.",
    "Machine learning enables computers to learn patterns from data.",
    "Deep learning uses neural networks with multiple layers.",
    "Pizza is a popular food enjoyed around the world.",
    "The weather forecast predicts rain tomorrow."
]

document_embeddings = embedding_model.encode(documents)
query_embedding = embedding_model.encode([query])

scores = cosine_similarity(
    query_embedding,
    document_embeddings
)[0]

print("DOCUMENT SIMILARITY SCORES\n")

for document, score in zip(documents, scores):
    print(f"{score:.4f} -> {document}")

# Rank documents from most similar to least similar
ranked_results = sorted(
    zip(documents, scores),
    key=lambda item: item[1],
    reverse=True
)

print("RANKED RESULTS\n")

for rank, (document, score) in enumerate(ranked_results, start=1):
    print(f"{rank}. Score: {score:.4f}")
    print(f"   {document}\n")